/* Cap Véto France — calculs vérifiables, sans backend ni suivi externe.
   Les taux historiques ne permettent PAS une probabilité personnelle d'admission.
*/
'use strict';
const KEY='cap-veto-france-private-v1';
const VERSION='1.1 · GitHub Pages';
const OFFICIAL_BAC='https://www.education.gouv.fr/reussir-au-lycee/comment-calculer-votre-note-au-baccalaureat-325511';
const REPORT_2026='https://www.concours-veto-postbac.fr/wp-content/uploads/2026/09/Rapport_Concours_ENVF_Public_2026_VD.pdf';
const ENV_CAL='https://www.concours-veto-postbac.fr/';
const CRITERIA='https://www.concours-veto-postbac.fr/concours/admissibilite/';
const SOURCES=[
 ['Ministère de l’Éducation nationale — coefficients du baccalauréat 2027',OFFICIAL_BAC],
 ['Rapport officiel du concours vétérinaire post-bac 2026, tableaux I, VII, XII',REPORT_2026],
 ['Concours véto post-bac — calendrier 2027',ENV_CAL],
 ['Concours véto post-bac — admissibilité et pièces évaluées',CRITERIA]
];
const HIST={confirmed:3815,admissible:851,admitted:280,previousConfirmed:4293,previousAdmissible:840,previousAdmitted:280};
const ENVREF=[
 {key:'Anglais',label:'Anglais LVA',ref:17,admitted:17.3},
 {key:'Espagnol',label:'Espagnol LVB',ref:17.5,admitted:17.6},
 {key:'Histoire-géographie',label:'Histoire-géographie',ref:16.7,admitted:16.8},
 {key:'Physique-chimie',label:'Physique-chimie spé',ref:16.8,admitted:17.3},
 {key:'SVT',label:'SVT spé',ref:17.3,admitted:17.2},
 {key:'fr_ecrit',label:'Français écrit (bac)',ref:15.3},
 {key:'fr_oral',label:'Français oral (bac)',ref:17.6}
];
const SUBJECTS=['Physique-chimie','SVT','Maths complémentaires','Anglais','Espagnol','Histoire-géographie','Enseignement scientifique','Philosophie','EPS','EMC'];
const BACCMP=[
 ['fr_ecrit','Français écrit · 2026',5,'confirmed',15],
 ['fr_oral','Français oral · 2026',5,'confirmed',15],
 ['math_ant','Maths anticipées · 2026',2,'confirmed',15],
 ['hg_1','Histoire-géographie · Première',3,'confirmed',15],
 ['hg_t','Histoire-géographie · Terminale',3,'term',16.0,'Histoire-géographie'],
 ['en_1','Anglais · Première',3,'confirmed',15],
 ['en_t','Anglais · Terminale',3,'term',18,'Anglais'],
 ['es_1','Espagnol · Première',3,'confirmed',15],
 ['es_t','Espagnol · Terminale',3,'term',18,'Espagnol'],
 ['sc_1','Enseignement scientifique · Première',3,'confirmed',15],
 ['sc_t','Enseignement scientifique · Terminale',3,'term',16,'Enseignement scientifique'],
 ['eps_t','EPS · CCF Terminale',6,'hyp',16],
 ['emc_1','EMC · Première',1,'confirmed',15],
 ['emc_t','EMC · Terminale',1,'term',17,'EMC'],
 ['spec_abandon','Maths spé abandonnée · Première',8,'confirmed',15],
 ['pc_exam','Épreuve de spécialité PC · 2027',16,'exam',16.7,'Physique-chimie'],
 ['svt_exam','Épreuve de spécialité SVT · 2027',16,'exam',16.4,'SVT'],
 ['philo_exam','Épreuve de philosophie · 2027',8,'hyp',15.5],
 ['oral_exam','Grand oral · 2027',8,'hyp',17],
 ['math_opt','Option maths complémentaires',2,'term',18,'Maths complémentaires']
];
const EVENT_LIST=[
 {id:'decouverte',when:'Oct. – Déc. 2026',title:'Comprendre le concours et les quatre ENV',detail:'Consulter les attendus, la fiche de formation et les forums d’information des écoles. Prévoir si possible une immersion auprès d’un vétérinaire.',verified:false,link:ENV_CAL},
 {id:'parcoursup',when:'Début 2027',title:'Constituer les vœux Parcoursup',detail:'Déposer les vœux, suivre les dates officiellement annoncées et vérifier les pièces demandées.',verified:false,link:'https://www.parcoursup.gouv.fr/'},
 {id:'questionnaire',when:'Avant confirmation du vœu',title:'Compléter le questionnaire d’auto-évaluation',detail:'Télécharger puis joindre l’attestation lorsque les règles de la session 2027 le requièrent. Le rapport 2026 rappelle cette formalité.',verified:false,link:CRITERIA},
 {id:'admissibilite',when:'Courant avril 2027',title:'Suivre la décision d’admissibilité',detail:'Surveiller Parcoursup et sa messagerie ; en cas d’admissibilité, réserver le créneau communiqué.',verified:false,link:ENV_CAL},
 {id:'epreuves',when:'Avril 2027',title:'Passer les épreuves d’admission',detail:'La période d’avril 2027 est annoncée par le concours. Dates et modalités pratiques à confirmer.',verified:true,link:ENV_CAL},
 {id:'resultats',when:'Début juin – été 2027',title:'Examiner les propositions d’admission',detail:'Suivre les propositions et les dates de réponse Parcoursup, puis choisir sa formation.',verified:false,link:'https://www.parcoursup.gouv.fr/'}
];
const $=x=>document.querySelector(x);
const clean=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(x,n=2)=>Number(x).toLocaleString('fr-FR',{minimumFractionDigits:n,maximumFractionDigits:n});
const clamp=(x,a,b)=>Math.min(b,Math.max(a,x));
const heading=(eyebrow,title,desc,buttons='')=>`<div class="page-header"><div><div class="eyebrow">${eyebrow}</div><h1 class="page-title">${title}</h1><p class="page-desc">${desc}</p></div>${buttons?`<div class="head-buttons">${buttons}</div>`:''}</div>`;
const btn=(label,action,cls='')=>`<button class="btn ${cls}" data-action="${action}">${label}</button>`;
const tag=(s,color='')=>`<span class="tag ${color}">${clean(s)}</span>`;
const card=(content,span='',extra='')=>`<section class="card ${span} ${extra}">${content}</section>`;
const emptyState=()=>`<section class="card empty"><div class="empty-icon">▤</div><h2>Ton dossier est prêt à être importé</h2><p>Le site ne contient aucune note personnelle dans son code. Importe <strong>MON_DOSSIER_PERSONNEL.json</strong> une seule fois : tes 9 notes, ton historique et les résultats officiels du bac apparaîtront immédiatement.</p>${btn('Importer mon dossier','import','primary')}<p class="micro" style="margin-top:14px">Le fichier reste dans ton navigateur. Aucune transmission vers un serveur.</p></section>`;
let state=readState();let route=(location.hash.slice(1)||'accueil');
function readState(){try {let s=JSON.parse(localStorage.getItem(KEY)||'null');return s?.schema==='cap-veto-france-v1'?s:null;}catch{return null;}}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));$('#save-status').textContent='Enregistré localement';}catch{$('#save-status').textContent='Stockage indisponible';toast('Stockage local indisponible : exporte une sauvegarde JSON.');}}
function toast(message){let el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3400);}
function grades(){return state?.grades||[];}
function averages(){let gr={};for(const g of grades()){if(!(g.subject in gr))gr[g.subject]={sum:0,weight:0,csum:0,cweight:0,n:0};const o=gr[g.subject],w=Number(g.coefficient);if(!(w>0))continue;o.sum+=Number(g.grade)*w;o.weight+=w;o.n++;if(Number.isFinite(g.classAvg)){o.csum+=Number(g.classAvg)*w;o.cweight+=w;}}
return Object.fromEntries(Object.entries(gr).map(([k,v])=>[k,{value:v.sum/v.weight,classAvg:v.cweight?v.csum/v.cweight:null,n:v.n,weight:v.weight}]));}
function isKnown(key){return Boolean(state?.confirmed&&Object.hasOwn(state.confirmed,key)&&state.confirmed[key]!==null&&Number.isFinite(Number(state.confirmed[key])));}
function projection(){let avg=averages(), overrides=state?.settings?.forecasts||{};
let parts=BACCMP.map(([key,label,coef,mode,def,subject])=>{let value=def,kind='hypothèse';
 if(mode==='confirmed'){value=isKnown(key)?Number(state.confirmed[key]):def;kind=isKnown(key)?'acquis':'référence à importer';}
 else if(Number.isFinite(Number(overrides[key]))&&overrides[key]!==null&&overrides[key]!==undefined){value=clamp(Number(overrides[key]),0,20);kind='simulé';}
 else if(mode==='term'&&avg[subject]){value=avg[subject].value;kind='provisoire';}
 else if(mode==='exam'&&avg[subject]){value=clamp(avg[subject].value-.65,0,20);kind='hypothèse d’examen';}
 return {key,label,coef,value,kind};});
let total=parts.reduce((a,x)=>a+x.value*x.coef,0),denom=parts.reduce((a,x)=>a+x.coef,0),earned=parts.filter(x=>x.kind==='acquis').reduce((a,x)=>a+x.coef,0);
let rangeDelta=parts.filter(x=>x.kind!=='acquis').reduce((a,x)=>a+x.coef,0)/denom; // +/-1.2 per remaining average; not CI
return {score:total/denom,denom,earned,parts,low:clamp(total/denom-1.2*rangeDelta,0,20),high:clamp(total/denom+1.2*rangeDelta,0,20)};}
function comparison(){let avg=averages();return ENVREF.map(r=>{let value=null,kind='Terminale provisoire';if(r.key.startsWith('fr_')){if(isKnown(r.key)){value=Number(state.confirmed[r.key]);kind='Note officielle';}}else if(avg[r.key])value=avg[r.key].value;return {...r,value,gap:value===null?null:value-r.ref,kind};});}
function scoreTag(d){if(d===null)return tag('Non renseigné');if(d>=.5)return tag('Au-dessus de la moyenne','green');if(d>=-.5)return tag('Proche de la moyenne','amber');return tag('En dessous de la moyenne','red');}
function metric(label,num,desc,icon='◈',ico=''){return card(`<div class="metric-label"><span>${label}</span><span class="metric-icon ${ico}">${icon}</span></div><div class="metric-num">${num}</div><div class="metric-foot">${desc}</div>`,'span-3','metric-card');}
function overview(){if(!state)return heading('TON ESPACE','L’essentiel, sans bruit','Notes, projection du bac et comparaison au concours national vétérinaire.')+emptyState();const av=averages(),p=projection(),comp=comparison();let bars=['Physique-chimie','SVT','Maths complémentaires','Anglais','Histoire-géographie'].filter(s=>av[s]).map(s=>{let x=av[s];return `<div class="compare-row"><div class="compare-top"><span>${clean(s)} <small>· ${x.n} évaluation${x.n>1?'s':''}</small></span><span class="compare-number">${fmt(x.value)} <em>/ 20</em></span></div><div class="track"><span class="fill" style="width:${x.value*5}%"></span>${x.classAvg!==null?`<span class="avgmark" title="Moyenne de classe ${fmt(x.classAvg)}" style="left:${x.classAvg*5}%"></span>`:''}</div></div>`}).join('');let crows=comp.filter(r=>r.value!==null).map(x=>`<tr><td><strong>${clean(x.label)}</strong></td><td class="num">${fmt(x.value)}</td><td class="num">${fmt(x.ref)}</td><td>${scoreTag(x.gap)}</td></tr>`).join('');let checked=Object.values(state.checks||{}).filter(Boolean).length;
return heading('TON TABLEAU DE BORD','Ton dossier, en perspective','Des résultats calculables et des repères statistiques pour préparer le concours vétérinaire français.',btn('Importer des données','import')+btn('Voir le bac →','goto-bac','primary'))+
`<div class="layout-grid">${metric('Bac 2027 · projection',`${fmt(p.score)} <span class="unit">/20</span>`,`${p.earned} / ${p.denom} coefficients acquis`,'◈')}${metric('Évaluations en Terminale',grades().length,`${state.history?.length||0} moyennes historiques`,'▤','blue')}${metric('Admissibles au concours 2026',`${fmt(HIST.admissible/HIST.confirmed*100,1)} %`,'Taux historique global, non personnel','◎')}${metric('Étapes suivies',`${checked} <span class="unit">/ ${EVENT_LIST.length}</span>`,'Liste de préparation','▣','orange')}</div>
<div class="section-row"><h2>Ton dossier aujourd’hui</h2><small>Dernière référence concours : session 2026</small></div><div class="layout-grid">
${card(`<div class="card-header"><h3 class="card-title">Moyennes de Terminale</h3><button class="text-link" data-action="goto-notes">Toutes les notes →</button></div><p class="card-sub">Barre colorée : ta moyenne. Marque verticale : la moyenne de classe lorsque connue.</p>${bars}`,'span-5')}
${card(`<div class="card-header"><h3 class="card-title">Face aux admissibles ENV</h3><button class="text-link" data-action="goto-env">Analyse complète →</button></div><p class="card-sub">Comparaison avec les moyennes publiées en 2026, et non avec le seuil du dernier admis.</p><div class="table-scroll"><table class="data-table"><thead><tr><th>Matière</th><th class="num">Toi</th><th class="num">Admissibles</th><th>Écart</th></tr></thead><tbody>${crows}</tbody></table></div><div class="side-note" style="margin-top:13px">Une note supérieure à la moyenne des admissibles ne garantit pas l’admissibilité. Le concours tient compte du dossier complet et de la fiche avenir.</div>`,'span-7')}
</div><div class="section-row"><h2>Comprendre les chiffres</h2></div><div class="layout-grid">${card(`<h3 class="card-title">Calcul du bac</h3><p class="card-sub">Les résultats officiels sont distingués des simulations et des moyennes provisoires.</p><div class="progress"><span class="earned" style="width:${p.earned/p.denom*100}%"></span><span class="estimated" style="width:${(p.denom-p.earned)/p.denom*100}%"></span></div><p class="micro muted">${p.earned} coefficients acquis · ${p.denom-p.earned} non acquis</p><p class="mini">Projection : <strong>${fmt(p.score)}/20</strong>. Scénario de variation illustrative ±1,2 point sur les coefficients non acquis : <strong>${fmt(p.low)}–${fmt(p.high)}</strong>.</p>${btn('Détail du calcul →','goto-bac')}`,'span-6')}
${card(`<h3 class="card-title">Prochaine étape</h3><p class="card-sub">Rester concentré sur la France, vérifier le dossier Parcoursup et préparer le concours.</p><div class="status-line"><span class="status-label">1. Se renseigner sur les quatre ENV</span>${tag('À faire','amber')}</div><div class="status-line"><span class="status-label">2. Vérifier les modalités 2027</span>${tag('À confirmer','amber')}</div><div class="status-line"><span class="status-label">3. Continuer tes spécialités</span>${tag('En cours','green')}</div>${btn('Voir le calendrier →','goto-calendrier')}`,'span-6')}</div>`;}
function notesPage(){if(!state)return heading('DOSSIER SCOLAIRE','Mes notes','Importe ton dossier personnel pour consulter et ajouter les évaluations.')+emptyState();let av=averages();let table=grades().slice().sort((a,b)=>b.date.localeCompare(a.date)).map(g=>`<tr><td>${clean(g.date)}</td><td><strong>${clean(g.subject)}</strong></td><td class="num">${fmt(g.grade)}</td><td class="num">${fmt(g.coefficient,2)}</td><td class="num">${g.classAvg===null?'—':fmt(g.classAvg)}</td><td class="num"><button class="btn small warn" data-action="delete-grade" data-id="${clean(g.id)}">Supprimer</button></td></tr>`).join('');const overview=Object.entries(av).sort((a,b)=>b[1].value-a[1].value).map(([s,a])=>`<tr><td><strong>${clean(s)}</strong></td><td class="num">${fmt(a.value)}</td><td class="num">${a.classAvg===null?'—':fmt(a.classAvg)}</td><td class="num">${a.n}</td></tr>`).join('');return heading('DONNÉES SCOLAIRES','Mes notes','Ajoute tes contrôles au fur et à mesure. L’application recalcule tes moyennes et le bac sans modifier les notes acquises.',btn('Exporter les notes CSV','export-csv')+btn('Sauvegarder le dossier','export','primary'))+
`<div class="layout-grid">${card(`<h3 class="card-title">Ajouter une évaluation</h3><p class="card-sub">Le coefficient est celui du contrôle dans la matière, pas le coefficient du bac.</p><form id="addgrade"><div class="form-grid"><div class="field"><label>Date</label><input required type="date" name="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Matière</label><select name="subject">${SUBJECTS.map(s=>`<option>${clean(s)}</option>`).join('')}</select></div><div class="field"><label>Note /20</label><input required name="grade" type="number" min="0" max="20" step="0.01" placeholder="18,5"></div><div class="field"><label>Coefficient</label><input required name="coefficient" type="number" min="0.01" max="100" step="any" value="1"></div><div class="field"><label>Moyenne de classe</label><input name="classAvg" type="number" min="0" max="20" step="0.01" placeholder="Optionnelle"></div></div><div class="form-actions"><button class="btn primary" type="submit">+ Ajouter la note</button>${btn('Importer une sauvegarde','import')}</div></form>`,'span-7')}
${card(`<h3 class="card-title">Moyennes actuelles</h3><p class="card-sub">Moyennes pondérées des évaluations réellement présentes dans le dossier.</p><div class="table-scroll"><table class="data-table"><thead><tr><th>Matière</th><th class="num">Toi</th><th class="num">Classe</th><th class="num">Notes</th></tr></thead><tbody>${overview}</tbody></table></div>`,'span-5')}
${card(`<h3 class="card-title">Historique des évaluations</h3><p class="card-sub">Suppression possible, aucune donnée envoyée à un serveur.</p><div class="table-scroll"><table class="data-table"><thead><tr><th>Date</th><th>Matière</th><th class="num">Note</th><th class="num">Coef.</th><th class="num">Classe</th><th></th></tr></thead><tbody>${table}</tbody></table></div>`)}
${historyCard()}</div>`;}
function subjectHistory(name){const hist=(state?.history||[]).filter(x=>x.subject===name);const yrOrder={'Troisième':0,'Seconde':1,'Première':2},pOrder={'T1':0,'S1':0,'T2':1,'S2':1,'T3':2};return hist.sort((a,b)=>yrOrder[a.year]-yrOrder[b.year]||pOrder[a.period]-pOrder[b.period]);}
function historyChart(rows){if(!rows.length)return '<div class="info-strip">Pas encore de données pour cette matière.</div>';const w=670,h=190,pad=34,dx=(w-2*pad)/(rows.length-1||1);const coords=rows.map((r,i)=>[pad+i*dx,h-pad-r.grade/20*(h-2*pad)]);const poly=coords.map(p=>p.join(',')).join(' ');let grid=[5,10,15,20].map(x=>`<line class="chart-grid" x1="${pad}" y1="${h-pad-x/20*(h-2*pad)}" x2="${w-pad}" y2="${h-pad-x/20*(h-2*pad)}"/><text class="chart-label" x="4" y="${h-pad-x/20*(h-2*pad)+3}">${x}</text>`).join('');return `<svg class="svg-chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="Évolution des moyennes par bulletin">${grid}<polyline class="chart-line" points="${poly}"/>${coords.map((p,i)=>`<circle class="chart-point" cx="${p[0]}" cy="${p[1]}" r="4"><title>${clean(rows[i].year)} ${clean(rows[i].period)} : ${fmt(rows[i].grade)}</title></circle><text class="chart-label" x="${p[0]}" y="${h-8}" text-anchor="middle">${clean(rows[i].year.slice(0,1))}${clean(rows[i].period)}</text>`).join('')}</svg>`;}
function historyCard(){let h=state?.history||[],names=[...new Set(h.map(x=>x.subject))].sort();if(!names.length)return '';let selected=state.settings?.historySubject||'Physique-chimie';if(!names.includes(selected))selected=names[0];const rows=subjectHistory(selected),table=rows.map(x=>`<tr><td>${clean(x.year)}</td><td>${clean(x.period)}</td><td class="num">${fmt(x.grade)}</td><td class="num">${x.classAvg===null?'—':fmt(x.classAvg)}</td><td class="num">${clean(x.rank||'—')}</td></tr>`).join('');return card(`<div class="card-header"><div><h3 class="card-title">Historique scolaire · Troisième à Première</h3><p class="card-sub">${h.length} moyennes de bulletin, distinctes des notes de contrôle.</p></div><select id="history-select" class="pill">${names.map(s=>`<option value="${clean(s)}" ${s===selected?'selected':''}>${clean(s)}</option>`).join('')}</select></div><div class="cols2"><div>${historyChart(rows)}</div><div class="table-scroll"><table class="data-table"><thead><tr><th>Année</th><th>Période</th><th class="num">Toi</th><th class="num">Classe</th><th class="num">Rang</th></tr></thead><tbody>${table}</tbody></table></div></div><div class="info-strip blue" style="margin-top:15px">Les résultats de Troisième et Seconde décrivent ton parcours, mais ne comptent pas directement au bac 2027 ni comme bulletins examinés au concours ENV post-bac.</div>`);}
function bacPage(){if(!state)return heading('BAC 2027','Une projection vérifiable','Les coefficients officiels sont déjà intégrés. Importe ton dossier pour ajouter tes résultats acquis.')+emptyState();let p=projection(),known=p.parts.filter(x=>x.kind==='acquis'),non=p.parts.filter(x=>x.kind!=='acquis');let rows=p.parts.map(x=>{let confirmed=x.kind==='acquis';return `<tr><td><strong>${clean(x.label)}</strong><br><span class="micro muted">${clean(x.kind)}</span></td><td class="num">${x.coef}</td><td class="num">${confirmed?`<strong>${fmt(x.value)}</strong>`:`<input class="num-input" aria-label="${clean(x.label)}" data-forecast="${x.key}" type="number" min="0" max="20" step="0.1" value="${Number(x.value.toFixed(2))}"/>`}</td><td class="num">${fmt(x.coef*x.value)}</td></tr>`}).join('');return heading('PROJECTION SCOLAIRE','Ton bac 2027','Une moyenne calculée avec les coefficients officiels. Modifie les hypothèses sans altérer les notes définitivement acquises.',btn('Réinitialiser les simulations','reset-forecasts')+btn('Sources du bac ↗','open-bac','primary'))+
`<div class="layout-grid">${metric('Projection centrale',`${fmt(p.score)} <span class="unit">/20</span>`,'Hypothèses et contrôles provisoires','◈')}${metric('Coefficients acquis',`${p.earned} <span class="unit">/ ${p.denom}</span>`,'Résultats officiels de Première','✓')}${metric('Coefficients non acquis',`${p.denom-p.earned}`,'Restent à évaluer / anticiper','◷','blue')}${metric('Simulation ± 1,2',`${fmt(p.low)} – ${fmt(p.high)}`,'Variation illustrative, non un IC','∿','orange')}
${card(`<h3 class="card-title">Répartition du calcul</h3><p class="card-sub">Vert : résultats officiels. Bleu : notes provisoires et hypothèses.</p><div class="progress"><span class="earned" style="width:${p.earned/p.denom*100}%"></span><span class="estimated" style="width:${(p.denom-p.earned)/p.denom*100}%"></span></div><div class="split" style="margin-top:15px"><span class="mini">Notes officiellement acquises</span><b>${p.earned} coefficients</b></div><div class="split"><span class="mini">Notes non acquises</span><b>${p.denom-p.earned} coefficients</b></div><div class="divider"></div><div class="side-note">L’option maths complémentaires ajoute 2 coefficients aux 100 coefficients obligatoires. Les moyennes de contrôle continu peuvent être harmonisées avant validation officielle.</div>`,'span-5')}
${card(`<h3 class="card-title">Pourquoi cette estimation reste incertaine</h3><p class="card-sub">Le bac n'est pas une simple extrapolation de moyenne générale.</p><div class="status-line"><span class="status-label">Épreuves anticipées</span>${tag('Résultats officiels','green')}</div><div class="status-line"><span class="status-label">Contrôle continu Terminale</span>${tag('Moyennes provisoires','amber')}</div><div class="status-line"><span class="status-label">Épreuves PC / SVT</span>${tag('Hypothèses ajustables','amber')}</div><div class="status-line"><span class="status-label">Philo / Grand oral / EPS</span>${tag('Hypothèses ajustables','amber')}</div><p class="method">Le scénario bas et haut suppose mécaniquement ±1,2 point sur chaque bloc non acquis : il ne s'agit pas d'une probabilité ni d'un intervalle de confiance empirique.</p>`,'span-7')}
${card(`<div class="card-header"><div><h3 class="card-title">Calcul détaillé des 102 coefficients</h3><p class="card-sub">Change une valeur et l'estimation est recalculée immédiatement. Les notes acquises ne sont pas éditables ici.</p></div>${tag('Formule officielle','green')}</div><div class="table-scroll"><table class="data-table"><thead><tr><th>Matière / épreuve</th><th class="num">Coefficient</th><th class="num">Note /20</th><th class="num">Points</th></tr></thead><tbody>${rows}<tr style="background:#f3faf8;font-weight:800"><td>TOTAL</td><td class="num">${p.denom}</td><td class="num">${fmt(p.score)}</td><td class="num">${fmt(p.score*p.denom)}</td></tr></tbody></table></div><p class="table-note">Formule : somme(note × coefficient) / somme(coefficients). Les valeurs modifiées sont conservées comme simulations dans ce navigateur.</p>`)}</div>`;}
function envPage(){if(!state)return heading('CONCOURS ENV','Ton dossier face au concours','Le rapport 2026 fournit les chiffres de référence ; importe tes notes pour établir la comparaison.')+`<div class="layout-grid">${admissionStats()}</div>`+emptyState();let c=comparison(),rows=c.map(x=>`<tr><td><strong>${clean(x.label)}</strong><br><span class="micro muted">${clean(x.kind)}</span></td><td class="num">${x.value===null?'—':fmt(x.value)}</td><td class="num">${fmt(x.ref)}</td><td class="num">${x.gap===null?'—':`<span class="${x.gap>=0?'gap-pos':'gap-neg'}">${x.gap>0?'+':''}${fmt(x.gap)}</span>`}</td><td>${scoreTag(x.gap)}</td></tr>`).join('');let comp=c.filter(x=>x.gap!==null);let up=comp.filter(x=>x.gap>=.5).length,close=comp.filter(x=>x.gap>=-.5&&x.gap<.5).length,down=comp.filter(x=>x.gap<-.5).length;
return heading('CONCOURS POST-BAC','Ton dossier face aux ENV','Comparaison avec les moyennes des 851 admissibles de 2026 — ce n’est ni un classement reconstitué ni une probabilité personnelle.',btn('Ouvrir le rapport 2026 ↗','open-report','primary'))+
`<div class="layout-grid">${admissionStats()}${card(`<div class="card-header"><h3 class="card-title">Écarts par matière</h3>${tag('Référence 2026','blue')}</div><p class="card-sub">Couleur fondée sur la différence à la moyenne du groupe, pas sur une « chance » d'admission.</p><div class="table-scroll"><table class="data-table"><thead><tr><th>Critère</th><th class="num">Toi</th><th class="num">Moy. admissibles</th><th class="num">Écart</th><th>Position</th></tr></thead><tbody>${rows}</tbody></table></div><div class="info-strip warn" style="margin-top:18px">Une moyenne des admissibles n'est pas une note minimale d'entrée : des dossiers différents ont été sélectionnés. Les notes de Terminale affichées ici reposent encore sur très peu de contrôles.</div>`,'span-8')}
${card(`<h3 class="card-title">Lecture de ton dossier</h3><p class="card-sub">Seuls les écarts effectivement calculables sont comptés.</p><div class="status-line"><span class="status-label">Au-dessus d'au moins 0,5 pt</span><b>${up}</b></div><div class="status-line"><span class="status-label">À ± 0,5 pt de la moyenne</span><b>${close}</b></div><div class="status-line"><span class="status-label">En dessous de plus de 0,5 pt</span><b>${down}</b></div><div class="divider"></div><p class="method">Ta doublette PC/SVT et l’option maths complémentaires correspondent aux choix recommandés. Le français écrit 13/20 est inférieur à la moyenne 15,3/20 observée chez les admissibles.</p><p class="method">Le jury prend aussi en compte l'ensemble des notes de Première, la fiche Avenir et d'autres critères, non chiffrables ici.</p>`,'span-4')}
${card(`<h3 class="card-title">Deux étapes indépendantes dans le classement</h3><div class="cols2"><div class="side-note"><strong>1. Admissibilité</strong><p>Résultats des bulletins de Première et Terminale, français anticipé, éléments qualitatifs de la fiche avenir. En 2026 : ${HIST.admissible} admissibles.</p></div><div class="side-note"><strong>2. Admission</strong><p>Épreuves de raisonnement, entretiens et QCM. En 2026, les points d'admissibilité ne sont pas reportés sur le classement final.</p></div></div><p class="table-note">Les épreuves 2027 peuvent évoluer : vérifier le règlement publié pour cette session.</p>`)}</div>`;}
function admissionStats(){return metric('Candidatures confirmées',fmt(HIST.confirmed,0),'Session 2026, rapport officiel','◉','blue')+metric('Admissibles',fmt(HIST.admissible,0),`${fmt(HIST.admissible/HIST.confirmed*100,1)} % des candidats`,'◇')+metric('Admis',fmt(HIST.admitted,0),`${fmt(HIST.admitted/HIST.confirmed*100,1)} % des candidats`,'✓')+metric('Admission après admissibilité',`${fmt(HIST.admitted/HIST.admissible*100,1)} %`,'Statistique historique, pas individuelle','↗','orange');}
function calendarPage(){let checks=state?.checks||{},count=Object.values(checks).filter(Boolean).length;let events=EVENT_LIST.map(e=>`<div class="event"><div class="event-date">${clean(e.when)}</div><div class="event-axis"><span class="event-dot"></span></div><div class="event-content"><div class="split"><h3 class="event-title">${clean(e.title)}</h3>${tag(e.verified?'Période annoncée':'À confirmer',e.verified?'green':'amber')}</div><p>${clean(e.detail)}</p><div class="split"><label class="checkbox-line" style="border:0;padding:0"><input type="checkbox" data-check="${e.id}" ${checks[e.id]?'checked':''}/> Étape préparée / vérifiée</label><a class="source-link" href="${e.link}" target="_blank" rel="noopener noreferrer">Source ↗</a></div></div></div>`).join('');return heading('ORGANISATION','Calendrier 2026–2027','Un calendrier de préparation : les dates officielles et les périodes indicatives ne sont jamais confondues.',tag(`${count} / ${EVENT_LIST.length} étapes suivies`))+
`<div class="layout-grid">${card(`<h3 class="card-title">Les prochaines étapes</h3><p class="card-sub">L'objectif est de ne pas manquer une formalité, pas de remplir chaque journée de tâches.</p><div class="timeline">${events}</div>`,'span-8')}
${card(`<h3 class="card-title">Priorités actuellement</h3><p class="card-sub">Ce qui peut être utile dès octobre.</p><div class="status-line"><span class="status-label">Préserver des résultats solides en PC/SVT</span>${tag('En cours','green')}</div><div class="status-line"><span class="status-label">Comprendre la voie post-bac</span>${tag('À faire','amber')}</div><div class="status-line"><span class="status-label">Se renseigner sur les métiers ruraux</span>${tag('À explorer','blue')}</div><div class="divider"></div><div class="info-strip warn">Les dates détaillées de Parcoursup 2027 et des épreuves doivent être vérifiées sur les sites officiels lorsqu'elles sont publiées. Une préparation conseillée n'est pas une obligation réglementaire.</div>`,'span-4')}</div>`;}
function dataPage(){return heading('DONNÉES & MÉTHODE','Un outil vérifiable','La transparence des sources compte autant que les calculs.',btn('Importer mon dossier','import')+btn('Exporter une sauvegarde','export','primary'))+
`<div class="layout-grid">${card(`<h3 class="card-title">Confidentialité du site</h3><p class="card-sub">L'application se présente sans ton dossier : toutes les données personnelles sont chargées après importation dans ce navigateur.</p><div class="info-strip">Aucune note, nom, adresse, date de naissance ou numéro de candidat ne figure dans les fichiers du site public. Les données importées restent dans le stockage local du navigateur, et les calculs sont effectués sur l'appareil.</div><p class="method">Attention : vider les données Safari ou passer sur un autre appareil peut supprimer l'accès à ton dossier local. Exporte régulièrement une sauvegarde JSON dans un endroit privé.</p>${state?`<div class="stat-band"><div class="block"><strong>${grades().length}</strong><small>Évaluations</small></div><div class="block"><strong>${state.history?.length||0}</strong><small>Moyennes historiques</small></div><div class="block"><strong>${Object.keys(state.confirmed||{}).length}</strong><small>Notes officielles</small></div></div>`:'<p class="muted mini">Aucun dossier importé pour le moment.</p>'}<div class="form-actions">${btn('Importer JSON','import')}${btn('Exporter JSON','export')}${btn('Réinitialiser','reset','warn')}</div>`,'span-7')}
${card(`<h3 class="card-title">Règles et formules</h3><p class="method"><strong>Moyenne de matière</strong> : somme(notes × coefficients) / somme(coefficients).</p><p class="method"><strong>Bac</strong> : somme(notes × coefficients officiels) / 102 si l'option maths complémentaires est suivie uniquement en Terminale.</p><p class="method"><strong>Comparaison ENV</strong> : moyenne de la matière − moyenne 2026 des admissibles. Aucun seuil personnel ou percentile ne peut être déduit de cette seule moyenne.</p><p class="method"><strong>Fourchette du bac</strong> : variation mécanique de ±1,2 point sur les blocs non acquis. Ce n'est pas un intervalle statistiquement calibré.</p>${tag('Modèle explicite · pas de pourcentage inventé','green')}`,'span-5')}
${card(`<h3 class="card-title">Sources officielles consultables</h3><p class="card-sub">Les données officielles de 2026 servent de références historiques. Les procédures 2027 peuvent évoluer.</p><ol class="ref-list">${SOURCES.map(s=>`<li><a href="${s[1]}" target="_blank" rel="noopener noreferrer" class="source-link">${clean(s[0])} ↗</a></li>`).join('')}</ol><div class="info-strip blue">Pour automatiser l'import des notes depuis le logiciel scolaire, il faudra un connecteur séparé et autorisé. Aucune connexion à l'ENT n'est actuellement effectuée.</div>`)}</div>`;}
function render(){route=location.hash.slice(1)||'accueil';if(!['accueil','notes','bac','env','calendrier','donnees'].includes(route))route='accueil';for(let n of document.querySelectorAll('[data-route]'))n.classList.toggle('active',n.dataset.route===route);const pages={accueil:overview,notes:notesPage,bac:bacPage,env:envPage,calendrier:calendarPage,donnees:dataPage};$('#main').innerHTML=pages[route]();document.title=`Cap Véto France — ${route==='accueil'?'Vue d’ensemble':route}`;}
function goto(r){location.hash=r;render();window.scrollTo({top:0,behavior:'instant'});$('#sidebar').classList.remove('open');}
function triggerDownload(name,type,content){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);}
function csvExport(){const col=['date','matiere','note','coefficient','moyenne_classe','annee'];const cell=v=>`"${String(v??'').replace(/"/g,'""')}"`;let rows=[col.join(',')];for(let g of grades())rows.push([g.date,g.subject,g.grade,g.coefficient,g.classAvg,'Terminale'].map(cell).join(','));triggerDownload('mes_notes_terminale.csv','text/csv;charset=utf-8','\ufeff'+rows.join('\r\n'));}
function action(name,id){if(name==='import'){$('#importfile').click();return;}if(name==='export'){if(!state){toast('Rien à exporter pour l’instant.');return;}triggerDownload('Sauvegarde_Cap_Veto_France.json','application/json;charset=utf-8',JSON.stringify({...state,savedAt:new Date().toISOString()},null,2));return;}
if(name==='export-csv'){csvExport();return;}if(name==='reset'){if(!state)return;if(!confirm('Effacer toutes les notes et les données locales de ce navigateur ? Fais une sauvegarde avant.'))return;state=null;localStorage.removeItem(KEY);render();toast('Dossier local réinitialisé.');return;}
if(name==='reset-forecasts'){if(state?.settings){state.settings.forecasts={};persist();render();toast('Hypothèses de simulation réinitialisées.');}return;}
if(name==='delete-grade'){if(!state||!confirm('Supprimer cette note ?'))return;state.grades=state.grades.filter(x=>String(x.id)!==String(id));persist();render();toast('Note supprimée.');return;}
if(name==='goto-bac')return goto('bac');if(name==='goto-notes')return goto('notes');if(name==='goto-env')return goto('env');if(name==='goto-calendrier')return goto('calendrier');if(name==='open-bac')return window.open(OFFICIAL_BAC,'_blank','noopener');if(name==='open-report')return window.open(REPORT_2026,'_blank','noopener');}
function validateImport(o){
  if(!o||o.schema!=='cap-veto-france-v1'||!Array.isArray(o.grades)||!Array.isArray(o.history)||!o.confirmed||typeof o.confirmed!=='object'||Array.isArray(o.confirmed))throw Error('Fichier incompatible avec Cap Véto France.');
  if(o.grades.length>5000||o.history.length>10000)throw Error('Fichier trop volumineux.');
  // Les objets importés sont reconstruits champ par champ : aucune donnée libre n'est injectée dans le DOM.
  const valid=(n,min=0,max=20)=>typeof n==='number'&&Number.isFinite(n)&&n>=min&&n<=max;
  const optNumber=(n)=>n===null||n===undefined?null:(valid(n)?n:NaN);
  const grades=o.grades.map((g,i)=>{
    if(!g||!SUBJECTS.includes(g.subject)||!valid(g.grade)||!valid(g.coefficient,.00001,100)||typeof g.date!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(g.date)||!Number.isFinite(optNumber(g.classAvg))&&optNumber(g.classAvg)!==null)throw Error('Une évaluation contient des valeurs non valides.');
    return {id:String(g.id??`import-${i}`).slice(0,80),date:g.date,subject:g.subject,grade:g.grade,coefficient:g.coefficient,classAvg:optNumber(g.classAvg)};
  });
  const hist=o.history.map(h=>{
    if(!h||typeof h.year!=='string'||typeof h.period!=='string'||typeof h.subject!=='string'||!valid(h.grade)||(!valid(h.classAvg)&&h.classAvg!==null&&h.classAvg!==undefined))throw Error('Une moyenne historique n’est pas valide.');
    if(!['Troisième','Seconde','Première','Terminale'].includes(h.year)||!['T1','T2','T3','S1','S2'].includes(h.period))throw Error('Période historique inconnue.');
    return {year:h.year,period:h.period,subject:h.subject.slice(0,100),grade:h.grade,classAvg:h.classAvg??null,rank:String(h.rank??'').slice(0,15)};
  });
  const confirmed={};
  const officialKeys=BACCMP.filter(p=>p[3]==='confirmed').map(p=>p[0]);
  for(const k of officialKeys){if(Object.hasOwn(o.confirmed,k)){if(!valid(o.confirmed[k]))throw Error('Une note officielle est invalide.');confirmed[k]=o.confirmed[k];}}
  const settings={forecasts:{},historySubject:'Physique-chimie'};
  if(o.settings&&typeof o.settings==='object'){
    if(typeof o.settings.historySubject==='string')settings.historySubject=o.settings.historySubject.slice(0,100);
    if(o.settings.forecasts&&typeof o.settings.forecasts==='object')for(const [key,n] of Object.entries(o.settings.forecasts)){
      if(BACCMP.some(p=>p[0]===key&&p[3]!=='confirmed')&&valid(n))settings.forecasts[key]=n;
    }
  }
  const checks={};for(const ev of EVENT_LIST)if(o.checks?.[ev.id]===true)checks[ev.id]=true;
  return {schema:'cap-veto-france-v1',grades,history:hist,confirmed,settings,checks,savedAt:new Date().toISOString()};
}
$('#importfile').addEventListener('change',async e=>{let f=e.target.files[0];if(!f)return;try{if(f.size>5*1024*1024)throw Error('Ce fichier dépasse la taille autorisée (5 Mo).');let imported=validateImport(JSON.parse(await f.text()));if(state&&grades().length&&!confirm('Remplacer le dossier actuel par celui du fichier ?'))return;state=imported;persist();render();toast(`Dossier importé : ${state.grades.length} notes et ${state.history.length} moyennes historiques.`);}catch(err){toast(err.message);}finally{e.target.value='';}});
$('#main').addEventListener('click',e=>{const target=e.target.closest('[data-action]');if(target){e.preventDefault();action(target.dataset.action,target.dataset.id);}});
$('#main').addEventListener('change',e=>{if(!state)return;const t=e.target;if(t.matches('[data-forecast]')){const x=Number(t.value);if(!(x>=0&&x<=20)){toast('La note doit être entre 0 et 20.');return;}state.settings??={};state.settings.forecasts??={};state.settings.forecasts[t.dataset.forecast]=x;persist();render();toast('Scénario recalculé.');}
if(t.matches('[data-check]')){state.checks??={};state.checks[t.dataset.check]=t.checked;persist();render();}
if(t.id==='history-select'){state.settings??={};state.settings.historySubject=t.value;persist();render();}});
$('#main').addEventListener('submit',e=>{if(e.target.id!=='addgrade')return;e.preventDefault();if(!state)return;const d=new FormData(e.target),grade=Number(d.get('grade')),coef=Number(d.get('coefficient'));const ca=String(d.get('classAvg')||'').trim(),classAvg=ca===''?null:Number(ca);if(!(grade>=0&&grade<=20&&coef>0&&coef<=100&&(classAvg===null||classAvg>=0&&classAvg<=20)))return toast('Vérifie les valeurs de la note.');state.grades.push({id:'added-'+Date.now()+'-'+Math.random().toString(16).slice(2),date:String(d.get('date')),subject:String(d.get('subject')),grade,coefficient:coef,classAvg});persist();render();toast('Note ajoutée, bac et comparaisons mis à jour.');});
$('#top-import').addEventListener('click',()=>action('import'));
$('#menubtn').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
window.addEventListener('hashchange',render);
// Expose pure, read-only functions for automated browser QA. Never expose imported file content.
window.CapVetoQA={projection,averages,comparison,getCount:()=>grades().length,coefficientSum:()=>BACCMP.reduce((a,x)=>a+x[2],0)};
render();
